# Generated by Django 3.0.5 on 2021-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('offer_price', models.CharField(max_length=30)),
                ('actual_price', models.CharField(max_length=30)),
            ],
        ),
    ]
